"""
Print compact API signatures for all public encrypted_cache classes to stdout.

Usage:
    uv run python scripts/AGENTS_gen_signatures.py
    # or redirect:
    uv run python scripts/AGENTS_gen_signatures.py > doc/AGENTS_api_signatures.txt
"""

import inspect
import sys
from pathlib import Path

# Ensure the repo src is on sys.path so the package can be imported
_REPO_ROOT = Path(__file__).parent.parent
_SRC = _REPO_ROOT / "src"
for _p in [str(_REPO_ROOT), str(_SRC)]:
    if _p not in sys.path:
        sys.path.insert(0, _p)


def _first_docstring_line(obj) -> str:
    doc = inspect.getdoc(obj)
    if not doc:
        return ""
    return doc.splitlines()[0].strip()


def _format_signature(name: str, obj) -> str:
    try:
        sig = inspect.signature(obj)
    except (ValueError, TypeError):
        sig = "()"
    return f"{name}{sig}"


def _own_public_methods(cls) -> list[tuple[str, object]]:
    """Return public methods defined directly on *cls* (not inherited from object or third-party bases)."""
    members = [
        (name, val)
        for name, val in vars(cls).items()
        if not name.startswith("_") and callable(val)
    ]
    return sorted(members)


def _public_module_functions(module) -> list[tuple[str, object]]:
    """Return public functions defined in *module* (not imported ones)."""
    members = [
        (name, obj)
        for name, obj in inspect.getmembers(module, inspect.isfunction)
        if not name.startswith("_") and obj.__module__ == module.__name__
    ]
    return sorted(members)


def print_class_signatures(cls, access_expr: str) -> None:
    print(f"## {cls.__name__}  ({access_expr})")
    print()
    for name, method in _own_public_methods(cls):
        sig_str = _format_signature(name, method)
        first_line = _first_docstring_line(method)
        print(sig_str)
        if first_line:
            print(f"    # {first_line}")
        print()
    print()


def main() -> None:
    import encrypted_cache as ec
    from encrypted_cache import EncryptedCache

    print("# encrypted_cache — compact API signatures")
    print("# Generated by scripts/AGENTS_gen_signatures.py")
    print("# Run: uv run python scripts/AGENTS_gen_signatures.py")
    print()

    print("## Module-level functions")
    print()
    for name, func in _public_module_functions(ec.core):
        print(_format_signature(name, func))
        first_line = _first_docstring_line(func)
        if first_line:
            print(f"    # {first_line}")
        print()
    print()

    print_class_signatures(EncryptedCache, "from encrypted_cache import EncryptedCache")


if __name__ == "__main__":
    main()
